module.exports = {
  CLOUD_HARDWARE_MESSAGE : "touch",
  CLOUD_ACCOUNT_INFO_MESSAGE: "CLOUD_ACCOUNT_INFO_MESSAGE",
  CLOUD_CHANGE_PASSWARD_MESSAGE: "CLOUD_CHANGE_PASSWARD_MESSAGE",
  APPIFI_HARDWARE_MESSAGE : "APPIFI_HARDWARE_MESSAGE",
  APPIFI_ACCOUNT_INFO_MESSAGE : "APPIFI_ACCOUNT_INFO_MESSAGE" 
}